2023-04-06 09:08:54,225.225 /projects/b1139/environments/emodpy_alt/lib/python3.8/site-packages/idmtools/utils/file_parser.py:150 load_bin_file [ERROR] (138587,47570452685888) - No module named 'dtk'
Traceback (most recent call last):
  File "/projects/b1139/environments/emodpy_alt/lib/python3.8/site-packages/idmtools/utils/file_parser.py", line 146, in load_bin_file
    from dtk.tools.output.SpatialOutput import SpatialOutput
ModuleNotFoundError: No module named 'dtk'
2023-04-06 09:08:54,230.230 /projects/b1139/environments/emodpy_alt/lib/python3.8/site-packages/idmtools/utils/file_parser.py:151 load_bin_file [ERROR] (138587,47570452685888) - Could not import item. Most likely dtk.tools is not installed
2023-04-06 09:08:54,248.248 /projects/b1139/environments/emodpy_alt/lib/python3.8/site-packages/idmtools/utils/file_parser.py:150 load_bin_file [ERROR] (138587,47570452685888) - No module named 'dtk'
Traceback (most recent call last):
  File "/projects/b1139/environments/emodpy_alt/lib/python3.8/site-packages/idmtools/utils/file_parser.py", line 146, in load_bin_file
    from dtk.tools.output.SpatialOutput import SpatialOutput
ModuleNotFoundError: No module named 'dtk'
2023-04-06 09:08:54,249.249 /projects/b1139/environments/emodpy_alt/lib/python3.8/site-packages/idmtools/utils/file_parser.py:151 load_bin_file [ERROR] (138587,47570452685888) - Could not import item. Most likely dtk.tools is not installed
2023-04-06 09:08:54,249.249 /projects/b1139/environments/emodpy_alt/lib/python3.8/site-packages/idmtools/utils/file_parser.py:150 load_bin_file [ERROR] (138587,47570452685888) - No module named 'dtk'
Traceback (most recent call last):
  File "/projects/b1139/environments/emodpy_alt/lib/python3.8/site-packages/idmtools/utils/file_parser.py", line 146, in load_bin_file
    from dtk.tools.output.SpatialOutput import SpatialOutput
ModuleNotFoundError: No module named 'dtk'
2023-04-06 09:08:54,249.249 /projects/b1139/environments/emodpy_alt/lib/python3.8/site-packages/idmtools/utils/file_parser.py:151 load_bin_file [ERROR] (138587,47570452685888) - Could not import item. Most likely dtk.tools is not installed
2023-04-06 09:08:54,249.249 /projects/b1139/environments/emodpy_alt/lib/python3.8/site-packages/idmtools/utils/file_parser.py:150 load_bin_file [ERROR] (138587,47570452685888) - No module named 'dtk'
Traceback (most recent call last):
  File "/projects/b1139/environments/emodpy_alt/lib/python3.8/site-packages/idmtools/utils/file_parser.py", line 146, in load_bin_file
    from dtk.tools.output.SpatialOutput import SpatialOutput
ModuleNotFoundError: No module named 'dtk'
2023-04-06 09:08:54,249.249 /projects/b1139/environments/emodpy_alt/lib/python3.8/site-packages/idmtools/utils/file_parser.py:151 load_bin_file [ERROR] (138587,47570452685888) - Could not import item. Most likely dtk.tools is not installed
2023-04-06 09:08:54,249.249 /projects/b1139/environments/emodpy_alt/lib/python3.8/site-packages/idmtools/analysis/map_worker_entry.py:101 _get_mapped_data_for_item [ERROR] (138587,47570452685888) - 'NoneType' object is not subscriptable
